### ISSUE TITLE
Solution on GitHub does not load in Visual Studio for Mac.

### ISSUE THREAD

**Issue by nekoniaow** [scemino/MO5-Emulator#2]
Hello/Salut,

there seems to be issues loading the solutions in the repository.

### What are you seeing ?
The solution file scemino/MO5-Emulator/MO5Emulator.sln does not load properly as a solution, it opens as a text file.
Similarly, the solution file scemino/MO5-Emulator/MO5Emulator/MO5Emulator.sln fails to load an App1.csproj project.

### What is expected?
The solution projects in the repository should be able to load fine.

### Steps to Reproduce
From a clean empty folder.
Clone the Git repository on Mac.
Open Visual Studio for Mac.
Try to open scemino/MO5-Emulator/MO5Emulator.sln, notice that it loads as a text file, not a solution.
Try to open scemino/MO5-Emulator/MO5Emulator/MO5Emulator.sln, note that it fails to load App1.csproj.

Thank you in advance.
Cheers,
Laurent

**Comment by scemino** [comment]
You're totally right, @nekoniaow !!
This is now fixed.
Thank you.

**Comment by scemino** [comment]
Can you confirm that the issue is fixed now @nekoniaow  ?

**Comment by nekoniaow** [comment]
Hi, sorry for the horribly long delay.
I unfortunately have not been able to test but I will do my best to give it a try this week end.

**Comment by nekoniaow** [comment]
I confirm that this was fixed, thanks!
The project builds correctly (on OS X with Visual Studio Mac).
However there is now an issue at runtime, I will create a new issue entry.
